name: Check website

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop, main]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Build and check site
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build --strict_front_matter
          python3 scripts/check_site.py
